self.addEventListener('install',e=>{
  e.waitUntil(caches.open('lm-v4').then(c=>c.addAll(['/','index.html','sw.js'])));
});
self.addEventListener('fetch',e=>e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request))));
self.addEventListener('notificationclick',e=>{
  e.notification.close();
  e.waitUntil(clients.openWindow('/'));
});
self.addEventListener('message',e=>{
  if(e.data&&e.data.type==='SHOW_NOTIF'){
    self.registration.showNotification(e.data.title,{
      body:e.data.body,
      icon:'icon-192.png',
      badge:'icon-192.png',
      tag:e.data.tag
    });
  }
});
